CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT IS IDENTITY NOT NULL,
    name VARCHAR NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT IS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL,
    title VARCHAR UNIQUE NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT IS IDENTITY NOT NULL,
    annotation TEXT NOT NULL,
    category_id BIGINT REFERENCES categories (id) ON DELETE SET NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    initiator_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    paid BOOLEAN NOT NULL,
    partipant_limit INT NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    views BIGINT NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilation (
    event_id BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT pk_event_compilation PRIMARY KEY (event_id, compilation_id)
);

CREATE TABLE IF NOT EXISTS participant_requests (
    id BIGINT GENERATED BY DEFAULT IS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status VARCHAR NOT NULL,
    CONSTRAINT pk_participant_request PRIMARY KEY (id)
);



