version: '3.1'
services:
  stat-server:
    build: ./stat-service/stat-server
    image: explore-with-me-stat
    container_name: explore-with-me-stat
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

#  basic-service:
#    build: ./basic-service
#    image: explore-with-me-basic
#    container_name: explore-with-me-basic
#    ports:
#      - "8080:8080"
#    depends_on:
#      - basic-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=ewm_user
#      - SPRING_DATASOURCE_PASSWORD=ewm_password
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
#
#  basic-db:
#    image: postgres:14-alpine
#    container_name: basic-db
#    ports:
#      - "6543:5432"
#    environment:
#      - POSTGRES_DB=ewm
#      - POSTGRES_USER=ewm_user
#      - POSTGRES_PASSWORD=ewm_password

